### PR TITLE
Add test driven development case for virtual chassis failure

### PR DESCRIPTION
**Pull request by itdependsnetworks**
Edit: I realized after the fact that this **should** work to run a single test from within the container in any version:

```shell
coverage run --module nautobot.core.cli test nautobot_design_builder.tests.test_builder.TestGeneralDesigns.test_virtual_chassis_assigned --keepdb --buffer
```

As shown below, works in 2.0.1, but not on develop. I ran the command: `TEST_YAML_FILE=virtual_chassis_assigned.yaml coverage run --module nautobot.core.cli test nautobot_design_builder.tests.test_builder.TestGeneralDesigns --keepdb --buffer` to run tests. 

Unfortunately, you can't switch back and forth to without adjusting the function `_testcases` with

```python
def _testcases(data_dir):
    # This allows you to specify a specific test file to run
    search_chars = os.environ.get("TEST_YAML_FILE", ".yaml")
    for filename in os.listdir(data_dir):
        if filename.endswith(search_chars):
            with open(os.path.join(data_dir, filename), encoding="utf-8") as file:
                yield yaml.safe_load(file), filename
```

This shows the same test working on 2.0.1, but not on develop. In the background, I am updating `_testcases` since there is an issue with another test, and you can't get the `virtual_chassis_assigned.yaml` file to work.

```python
root@04892240e202:/source# git checkout v2.0.1
Note: switching to 'v2.0.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 98d1d45 Merge pull request #188 from nautobot/develop
####################################################
##### NOTE Showing on v.2.0.1 then tests pass ######
####################################################
root@04892240e202:/source# TEST_YAML_FILE=virtual_chassis_assigned.yaml coverage run --module nautobot.core.cli test nautobot_design_builder.tests.test_builder.TestGeneralDesigns --keepdb --buffer
Using NautobotPerformanceTestRunner to run tests ...
Found 1 test(s).
Using existing test database for alias 'default'...
System check identified no issues (0 silenced).
.
----------------------------------------------------------------------
Ran 1 test in 0.219s

OK
Preserving test database for alias 'default'...
root@04892240e202:/source# git checkout develop
Previous HEAD position was 98d1d45 Merge pull request #188 from nautobot/develop
Switched to branch 'develop'
Your branch is up to date with 'origin/develop'.

####################################################
##### NOTE Showing on develop then tests fail ######
####################################################
root@04892240e202:/source# TEST_YAML_FILE=virtual_chassis_assigned.yaml coverage run --module nautobot.core.cli test nautobot_design_builder.tests.test_builder.TestGeneralDesigns --keepdb --buffer
Using NautobotPerformanceTestRunner to run tests ...
Found 1 test(s).
Using existing test database for alias 'default'...
System check identified no issues (0 silenced).
E
======================================================================
ERROR: test_virtual_chassis_assigned (nautobot_design_builder.tests.test_builder.TestGeneralDesigns.test_virtual_chassis_assigned)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/source/nautobot_design_builder/tests/test_builder.py", line 180, in test_runner
    self._run_test_case(testcase, cls.data_dir)  # pylint:disable=protected-access
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/nautobot_design_builder/tests/test_builder.py", line 217, in _run_test_case
    environment.implement_design(design=design, commit=commit)
  File "/source/nautobot_design_builder/design.py", line 813, in implement_design
    raise ex
  File "/source/nautobot_design_builder/design.py", line 797, in implement_design
    self._create_objects(self.model_map[key], value)
  File "/source/nautobot_design_builder/design.py", line 897, in _create_objects
    model = model_class(self, model_instance)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/nautobot_design_builder/design.py", line 569, in __init__
    self.design_metadata.attributes = attributes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/nautobot_design_builder/design.py", line 252, in attributes
    self._attributes[key] = self.environment.resolve_values(self._attributes[key])
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/nautobot_design_builder/design.py", line 887, in resolve_values
    value[k] = self.resolve_value(item)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/nautobot_design_builder/design.py", line 851, in resolve_value
    value = extn.value(arg)
            ^^^^^^^^^^^^^^^
  File "/source/nautobot_design_builder/ext.py", line 211, in value
    adding = model_instance.design_instance._state.adding  # pylint: disable=protected-access
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_state'

----------------------------------------------------------------------
Ran 1 test in 0.148s

FAILED (errors=1)
Preserving test database for alias 'default'...
root@04892240e202:/source#
```

### CODE REVIEW

**Comment by itdependsnetworks** [comment]
@chadell this is side stepping the issue, not fixing it. When nested, it did work in 2.0.1, we should address that versus changing how to do this test.

**Review by chadell — APPROVED** [review]
LGTM
